export type TripDay={id:number,date:string,title:string,km:string,drive:string,stay:string,summary:string,timeline:{time:string,title:string,note?:string,critical?:boolean}[],priorities:string[],cuts:string[],fuel:string[],decision?:string};
export const days:TripDay[]=[
{id:1,date:'9月27日 周日',title:'抵达张掖',km:'约35 km',drive:'约45分钟',stay:'张掖市区',summary:'21:00抵达；当晚不安排景点。次日上午取车。',timeline:[{time:'上午',title:'询问车行能否提前取车',note:'若不能，9/28 自动执行“演出优先”。',critical:true},{time:'21:00',title:'抵达张掖机场'},{time:'22:00',title:'前往市区入住',note:'早点休息，不安排夜游。'}],priorities:['确认取车时间','保证睡眠'],cuts:['所有景点'],fuel:['确认第二天取车位置与材料']},
{id:2,date:'9月28日 周一',title:'七彩丹霞 → 敦煌',km:'约600–620 km',drive:'约7–8小时',stay:'敦煌市区',summary:'全程关键日。20:00《又见敦煌》优先，12:00必须离开丹霞。',timeline:[{time:'08:00',title:'张掖取车',note:'验车、拍全车视频、检查轮胎与随车工具。',critical:true},{time:'08:40',title:'根据取车结果决定丹霞',note:'不能提前取车时，极短游或取消。'},{time:'≤12:00',title:'务必离开七彩丹霞',note:'这是硬截止，不因排队延后。',critical:true},{time:'途中',title:'嘉峪关 / 瓜州休息加油',note:'只作补给，不增加关城景点。'},{time:'19:00前',title:'抵达敦煌并前往剧场',note:'不为赶场超速。'},{time:'20:00',title:'《又见敦煌》演出',critical:true}],priorities:['行车安全','《又见敦煌》20:00','七彩丹霞'],cuts:['嘉峪关关城','取车晚则缩短或取消丹霞'],fuel:['离开张掖前加满','嘉峪关/瓜州休息与补能'],decision:'取车无法提前 → 演出优先 → 丹霞降级。'},
{id:3,date:'9月29日 周二',title:'莫高窟 → 鸣沙山月牙泉',km:'约70 km',drive:'约1.5小时',stay:'敦煌市区',summary:'文化核心日，上午莫高窟固定场次，下午休息后看沙漠日落。',timeline:[{time:'08:40前',title:'抵达莫高窟数字展示中心',note:'实名证件与常规票。',critical:true},{time:'09:25',title:'莫高窟常规票预约场次',critical:true},{time:'中午',title:'回敦煌吃饭、休息'},{time:'约16:00',title:'鸣沙山月牙泉',note:'按当日开放时间调整，日落后返回。'}],priorities:['莫高窟常规票','鸣沙山月牙泉','市区闲逛'],cuts:['敦煌市区闲逛'],fuel:['市区补水、防晒、帽子']},
{id:4,date:'9月30日 周三',title:'敦煌 → 黑独山 → 水上雅丹',km:'约560–630 km',drive:'约8–9小时',stay:'水上雅丹景区外',summary:'强度最高的一天，不追日落，不在荒漠赶夜路。',timeline:[{time:'06:30',title:'敦煌出发',critical:true},{time:'上午',title:'当金山荒漠公路'},{time:'约45–60分',title:'黑独山短停',note:'天气或路况差立即跳过。'},{time:'中午',title:'冷湖吃饭、加油、补水',critical:true},{time:'傍晚前',title:'抵达水上雅丹景区外住宿',critical:true}],priorities:['安全抵达住宿','黑独山','当金山公路','冷湖停留'],cuts:['恶劣天气取消黑独山','冷湖只作补给'],fuel:['进入荒漠前加满','冷湖必须加油','饮水2–3L＋完整路餐'],decision:'大风 / 沙尘 / 雨雪 / 能见度差 → 跳过黑独山。'},
{id:5,date:'10月1日 周四',title:'水上雅丹 → G315 → 大柴旦',km:'约240 km',drive:'约3.5–4小时',stay:'大柴旦镇',summary:'上午水上雅丹，下午享受G315公路，翡翠湖完全弹性。',timeline:[{time:'上午',title:'水上雅丹',note:'预留3–4小时。'},{time:'午饭后',title:'沿G315向东',note:'只在合法安全停车区停留。'},{time:'16:00–17:00',title:'抵达大柴旦',note:'加油、检查车辆、早点休息。'},{time:'可选',title:'大柴旦翡翠湖',note:'仅抵达早、天气好、体力足时加入。'}],priorities:['水上雅丹','G315公路体验','翡翠湖'],cuts:['16:30后抵达则取消翡翠湖'],fuel:['大柴旦加满','检查胎压和玻璃水'],decision:'16:30后到达 / 疲劳 / 天气差 → 不去翡翠湖。'},
{id:6,date:'10月2日 周五',title:'大柴旦 → 茶卡盐湖',km:'约400 km',drive:'约5–5.5小时',stay:'茶卡镇',summary:'茶卡保留但不深游，不增加其他盐湖。',timeline:[{time:'08:00',title:'离开大柴旦'},{time:'中午',title:'德令哈午饭、加油、休息',critical:true},{time:'约15:30',title:'抵达茶卡盐湖',note:'游览1.5–2.5小时。'},{time:'傍晚',title:'茶卡镇入住'}],priorities:['安全到茶卡','茶卡盐湖'],cuts:['天气差或晚到压缩至1–1.5小时','不增加察尔汗或其他盐湖'],fuel:['德令哈加油','茶卡为最后一晚补齐路餐']},
{id:7,date:'10月3日 周六',title:'黑马河 → 西宁机场',km:'约300–340 km',drive:'约4.5–5.5小时',stay:'19:00 飞北京',summary:'只去黑马河正规观景台；机场目标15:30–16:00。',timeline:[{time:'06:30–07:00',title:'离开茶卡镇',critical:true},{time:'上午',title:'黑马河正规观景台',note:'停留30–60分钟，不追日出。'},{time:'可选',title:'日月山',note:'仅确认仍有超过2小时完整余量时加入。'},{time:'15:30–16:00',title:'抵达西宁机场',note:'加满油、还车、办理登机。',critical:true},{time:'19:00',title:'起飞返京',critical:true}],priorities:['按时抵达机场','黑马河观景台','日月山'],cuts:['导航预计16:30后到机场 → 取消全部停留','余量不足2小时 → 不去日月山','不去二郎剑、仙女湾、金沙湾'],fuel:['机场前加满并保留票据'],decision:'先锁定16:00到机场；实际完整余量>2小时，才可加入日月山。'}
];
export const initialTodos=[{id:'ticket-mogao',text:'确认莫高窟 9/29 09:25 常规票',group:'预订',done:false},{id:'show',text:'确认《又见敦煌》9/28 20:00演出票',group:'预订',done:false},{id:'car',text:'9/27上午询问车行能否提前取车',group:'关键',done:false},{id:'hotel-yadan',text:'确认水上雅丹景区外住宿与停车',group:'住宿',done:false},{id:'offline-map',text:'下载两套离线地图与每日路线',group:'安全',done:false},{id:'emergency',text:'准备2–3L水、路餐、保暖毯与药品',group:'补给',done:false},{id:'share',text:'把每日酒店和到达时间分享给家人',group:'安全',done:false},{id:'ids',text:'证件、驾照、充电器、票据备份',group:'出发',done:false}];
